<?php if (!defined('ABSPATH')) {
    exit; // exit if accessed directly
}

/**
 * Linea Icon Font
 * @return array
 * since 4.7.1
 */

function ut_iconpicker_type_lineaicons( $icons ) {
		
	$linea_icons = array(
	
		'Arrows' => array(
			array( "icon-arrows-anticlockwise" => "arrows-anticlockwise" ),
			array( "icon-arrows-anticlockwise-dashed" => "arrows-anticlockwise-dashed" ),
			array( "icon-arrows-button-down" => "arrows-button-down" ),
			array( "icon-arrows-button-off" => "arrows-button-off" ),
			array( "icon-arrows-button-on" => "arrows-button-on" ),
			array( "icon-arrows-button-up" => "arrows-button-up" ),
			array( "icon-arrows-check" => "arrows-check" ),
			array( "icon-arrows-circle-check" => "arrows-circle-check" ),
			array( "icon-arrows-circle-down" => "arrows-circle-down" ),
			array( "icon-arrows-circle-downleft" => "arrows-circle-downleft" ),
			array( "icon-arrows-circle-downright" => "arrows-circle-downright" ),
			array( "icon-arrows-circle-left" => "arrows-circle-left" ),
			array( "icon-arrows-circle-minus" => "arrows-circle-minus" ),
			array( "icon-arrows-circle-plus" => "arrows-circle-plus" ),
			array( "icon-arrows-circle-remove" => "arrows-circle-remove" ),
			array( "icon-arrows-circle-right" => "arrows-circle-right" ),
			array( "icon-arrows-circle-up" => "arrows-circle-up" ),
			array( "icon-arrows-circle-upleft" => "arrows-circle-upleft" ),
			array( "icon-arrows-circle-upright" => "arrows-circle-upright" ),
			array( "icon-arrows-clockwise" => "arrows-clockwise" ),
			array( "icon-arrows-clockwise-dashed" => "arrows-clockwise-dashed" ),
			array( "icon-arrows-compress" => "arrows-compress" ),
			array( "icon-arrows-deny" => "arrows-deny" ),
			array( "icon-arrows-diagonal" => "arrows-diagonal" ),
			array( "icon-arrows-diagonal2" => "arrows-diagonal2" ),
			array( "icon-arrows-down" => "arrows-down" ),
			array( "icon-arrows-down-double" => "arrows-down-double" ),
			array( "icon-arrows-downleft" => "arrows-downleft" ),
			array( "icon-arrows-downright" => "arrows-downright" ),
			array( "icon-arrows-drag-down" => "arrows-drag-down" ),
			array( "icon-arrows-drag-down-dashed" => "arrows-drag-down-dashed" ),
			array( "icon-arrows-drag-horiz" => "arrows-drag-horiz" ),
			array( "icon-arrows-drag-left" => "arrows-drag-left" ),
			array( "icon-arrows-drag-left-dashed" => "arrows-drag-left-dashed" ),
			array( "icon-arrows-drag-right" => "arrows-drag-right" ),
			array( "icon-arrows-drag-right-dashed" => "arrows-drag-right-dashed" ),
			array( "icon-arrows-drag-up" => "arrows-drag-up" ),
			array( "icon-arrows-drag-up-dashed" => "arrows-drag-up-dashed" ),
			array( "icon-arrows-drag-vert" => "arrows-drag-vert" ),
			array( "icon-arrows-exclamation" => "arrows-exclamation" ),
			array( "icon-arrows-expand" => "arrows-expand" ),
			array( "icon-arrows-expand-diagonal1" => "arrows-expand-diagonal1" ),
			array( "icon-arrows-expand-horizontal1" => "arrows-expand-horizontal1" ),
			array( "icon-arrows-expand-vertical1" => "arrows-expand-vertical1" ),
			array( "icon-arrows-fit-horizontal" => "arrows-fit-horizontal" ),
			array( "icon-arrows-fit-vertical" => "arrows-fit-vertical" ),
			array( "icon-arrows-glide" => "arrows-glide" ),
			array( "icon-arrows-glide-horizontal" => "arrows-glide-horizontal" ),
			array( "icon-arrows-glide-vertical" => "arrows-glide-vertical" ),
			array( "icon-arrows-hamburger1" => "arrows-hamburger1" ),
			array( "icon-arrows-hamburger-2" => "arrows-hamburger-2" ),
			array( "icon-arrows-horizontal" => "arrows-horizontal" ),
			array( "icon-arrows-info" => "arrows-info" ),
			array( "icon-arrows-keyboard-alt" => "arrows-keyboard-alt" ),
			array( "icon-arrows-keyboard-cmd" => "arrows-keyboard-cmd" ),
			array( "icon-arrows-keyboard-delete" => "arrows-keyboard-delete" ),
			array( "icon-arrows-keyboard-down" => "arrows-keyboard-down" ),
			array( "icon-arrows-keyboard-left" => "arrows-keyboard-left" ),
			array( "icon-arrows-keyboard-return" => "arrows-keyboard-return" ),
			array( "icon-arrows-keyboard-right" => "arrows-keyboard-right" ),
			array( "icon-arrows-keyboard-shift" => "arrows-keyboard-shift" ),
			array( "icon-arrows-keyboard-tab" => "arrows-keyboard-tab" ),
			array( "icon-arrows-keyboard-up" => "arrows-keyboard-up" ),
			array( "icon-arrows-left" => "arrows-left" ),
			array( "icon-arrows-left-double-32" => "arrows-left-double-32" ),
			array( "icon-arrows-minus" => "arrows-minus" ),
			array( "icon-arrows-move" => "arrows-move" ),
			array( "icon-arrows-move2" => "arrows-move2" ),
			array( "icon-arrows-move-bottom" => "arrows-move-bottom" ),
			array( "icon-arrows-move-left" => "arrows-move-left" ),
			array( "icon-arrows-move-right" => "arrows-move-right" ),
			array( "icon-arrows-move-top" => "arrows-move-top" ),
			array( "icon-arrows-plus" => "arrows-plus" ),
			array( "icon-arrows-question" => "arrows-question" ),
			array( "icon-arrows-remove" => "arrows-remove" ),
			array( "icon-arrows-right" => "arrows-right" ),
			array( "icon-arrows-right-double" => "arrows-right-double" ),
			array( "icon-arrows-rotate" => "arrows-rotate" ),
			array( "icon-arrows-rotate-anti" => "arrows-rotate-anti" ),
			array( "icon-arrows-rotate-anti-dashed" => "arrows-rotate-anti-dashed" ),
			array( "icon-arrows-rotate-dashed" => "arrows-rotate-dashed" ),
			array( "icon-arrows-shrink" => "arrows-shrink" ),
			array( "icon-arrows-shrink-diagonal1" => "arrows-shrink-diagonal1" ),
			array( "icon-arrows-shrink-diagonal2" => "arrows-shrink-diagonal2" ),
			array( "icon-arrows-shrink-horizonal2" => "arrows-shrink-horizonal2" ),
			array( "icon-arrows-shrink-horizontal1" => "arrows-shrink-horizontal1" ),
			array( "icon-arrows-shrink-vertical1" => "arrows-shrink-vertical1" ),
			array( "icon-arrows-shrink-vertical2" => "arrows-shrink-vertical2" ),
			array( "icon-arrows-sign-down" => "arrows-sign-down" ),
			array( "icon-arrows-sign-left" => "arrows-sign-left" ),
			array( "icon-arrows-sign-right" => "arrows-sign-right" ),
			array( "icon-arrows-sign-up" => "arrows-sign-up" ),
			array( "icon-arrows-slide-down1" => "arrows-slide-down1" ),
			array( "icon-arrows-slide-down2" => "arrows-slide-down2" ),
			array( "icon-arrows-slide-left1" => "arrows-slide-left1" ),
			array( "icon-arrows-slide-left2" => "arrows-slide-left2" ),
			array( "icon-arrows-slide-right1" => "arrows-slide-right1" ),
			array( "icon-arrows-slide-right2" => "arrows-slide-right2" ),
			array( "icon-arrows-slide-up1" => "arrows-slide-up1" ),
			array( "icon-arrows-slide-up2" => "arrows-slide-up2" ),
			array( "icon-arrows-slim-down" => "arrows-slim-down" ),
			array( "icon-arrows-slim-down-dashed" => "arrows-slim-down-dashed" ),
			array( "icon-arrows-slim-left" => "arrows-slim-left" ),
			array( "icon-arrows-slim-left-dashed" => "arrows-slim-left-dashed" ),
			array( "icon-arrows-slim-right" => "arrows-slim-right" ),
			array( "icon-arrows-slim-right-dashed" => "arrows-slim-right-dashed" ),
			array( "icon-arrows-slim-up" => "arrows-slim-up" ),
			array( "icon-arrows-slim-up-dashed" => "arrows-slim-up-dashed" ),
			array( "icon-arrows-square-check" => "arrows-square-check" ),
			array( "icon-arrows-square-down" => "arrows-square-down" ),
			array( "icon-arrows-square-downleft" => "arrows-square-downleft" ),
			array( "icon-arrows-square-downright" => "arrows-square-downright" ),
			array( "icon-arrows-square-left" => "arrows-square-left" ),
			array( "icon-arrows-square-minus" => "arrows-square-minus" ),
			array( "icon-arrows-square-plus" => "arrows-square-plus" ),
			array( "icon-arrows-square-remove" => "arrows-square-remove" ),
			array( "icon-arrows-square-right" => "arrows-square-right" ),
			array( "icon-arrows-square-up" => "arrows-square-up" ),
			array( "icon-arrows-square-upleft" => "arrows-square-upleft" ),
			array( "icon-arrows-square-upright" => "arrows-square-upright" ),
			array( "icon-arrows-squares" => "arrows-squares" ),
			array( "icon-arrows-stretch-diagonal1" => "arrows-stretch-diagonal1" ),
			array( "icon-arrows-stretch-diagonal2" => "arrows-stretch-diagonal2" ),
			array( "icon-arrows-stretch-diagonal3" => "arrows-stretch-diagonal3" ),
			array( "icon-arrows-stretch-diagonal4" => "arrows-stretch-diagonal4" ),
			array( "icon-arrows-stretch-horizontal1" => "arrows-stretch-horizontal1" ),
			array( "icon-arrows-stretch-horizontal2" => "arrows-stretch-horizontal2" ),
			array( "icon-arrows-stretch-vertical1" => "arrows-stretch-vertical1" ),
			array( "icon-arrows-stretch-vertical2" => "arrows-stretch-vertical2" ),
			array( "icon-arrows-switch-horizontal" => "arrows-switch-horizontal" ),
			array( "icon-arrows-switch-vertical" => "arrows-switch-vertical" ),
			array( "icon-arrows-up" => "arrows-up" ),
			array( "icon-arrows-up-double-33" => "arrows-up-double-33" ),
			// array( "icon-arrows-upleft" => "arrows-upleft" ),
			array( "icon-arrows-upright" => "arrows-upright" ),
			array( "icon-arrows-vertical" => "arrows-vertical" )
		),
		'Basic' => array(
			array( "icon-basic-accelerator" => "basic-accelerator" ),
			array( "icon-basic-alarm" => "basic-alarm" ),
			array( "icon-basic-anchor" => "basic-anchor" ),
			array( "icon-basic-anticlockwise" => "basic-anticlockwise" ),
			array( "icon-basic-archive" => "basic-archive" ),
			array( "icon-basic-archive-full" => "basic-archive-full" ),
			array( "icon-basic-ban" => "basic-ban" ),
			array( "icon-basic-battery-charge" => "basic-battery-charge" ),
			array( "icon-basic-battery-empty" => "basic-battery-empty" ),
			array( "icon-basic-battery-full" => "basic-battery-full" ),
			array( "icon-basic-battery-half" => "basic-battery-half" ),
			array( "icon-basic-bolt" => "basic-bolt" ),
			array( "icon-basic-book" => "basic-book" ),
			array( "icon-basic-book-pen" => "basic-book-pen" ),
			array( "icon-basic-book-pencil" => "basic-book-pencil" ),
			array( "icon-basic-bookmark" => "basic-bookmark" ),
			array( "icon-basic-calculator" => "basic-calculator" ),
			array( "icon-basic-calendar" => "basic-calendar" ),
			array( "icon-basic-cards-diamonds" => "basic-cards-diamonds" ),
			array( "icon-basic-cards-hearts" => "basic-cards-hearts" ),
			array( "icon-basic-case" => "basic-case" ),
			array( "icon-basic-chronometer" => "basic-chronometer" ),
			array( "icon-basic-clessidre" => "basic-clessidre" ),
			array( "icon-basic-clock" => "basic-clock" ),
			array( "icon-basic-clockwise" => "basic-clockwise" ),
			array( "icon-basic-cloud" => "basic-cloud" ),
			array( "icon-basic-clubs" => "basic-clubs" ),
			array( "icon-basic-compass" => "basic-compass" ),
			array( "icon-basic-cup" => "basic-cup" ),
			array( "icon-basic-diamonds" => "basic-diamonds" ),
			array( "icon-basic-display" => "basic-display" ),
			array( "icon-basic-download" => "basic-download" ),
			array( "icon-basic-exclamation" => "basic-exclamation" ),
			array( "icon-basic-eye" => "basic-eye" ),
			array( "icon-basic-eye-closed" => "basic-eye-closed" ),
			array( "icon-basic-female" => "basic-female" ),
			array( "icon-basic-flag1" => "basic-flag1" ),
			array( "icon-basic-flag2" => "basic-flag2" ),
			array( "icon-basic-floppydisk" => "basic-floppydisk" ),
			array( "icon-basic-folder" => "basic-folder" ),
			array( "icon-basic-folder-multiple" => "basic-folder-multiple" ),
			array( "icon-basic-gear" => "basic-gear" ),
			array( "icon-basic-geolocalize-01" => "basic-geolocalize-01" ),
			array( "icon-basic-geolocalize-05" => "basic-geolocalize-05" ),
			array( "icon-basic-globe" => "basic-globe" ),
			array( "icon-basic-gunsight" => "basic-gunsight" ),
			array( "icon-basic-hammer" => "basic-hammer" ),
			array( "icon-basic-headset" => "basic-headset" ),
			array( "icon-basic-heart" => "basic-heart" ),
			array( "icon-basic-heart-broken" => "basic-heart-broken" ),
			array( "icon-basic-helm" => "basic-helm" ),
			array( "icon-basic-home" => "basic-home" ),
			array( "icon-basic-info" => "basic-info" ),
			array( "icon-basic-ipod" => "basic-ipod" ),
			array( "icon-basic-joypad" => "basic-joypad" ),
			array( "icon-basic-key" => "basic-key" ),
			array( "icon-basic-keyboard" => "basic-keyboard" ),
			array( "icon-basic-laptop" => "basic-laptop" ),
			array( "icon-basic-life-buoy" => "basic-life-buoy" ),
			array( "icon-basic-lightbulb" => "basic-lightbulb" ),
			array( "icon-basic-link" => "basic-link" ),
			array( "icon-basic-lock" => "basic-lock" ),
			array( "icon-basic-lock-open" => "basic-lock-open" ),
			array( "icon-basic-magic-mouse" => "basic-magic-mouse" ),
			array( "icon-basic-magnifier" => "basic-magnifier" ),
			array( "icon-basic-magnifier-minus" => "basic-magnifier-minus" ),
			array( "icon-basic-magnifier-plus" => "basic-magnifier-plus" ),
			array( "icon-basic-mail" => "basic-mail" ),
			array( "icon-basic-mail-multiple" => "basic-mail-multiple" ),
			array( "icon-basic-mail-open" => "basic-mail-open" ),
			array( "icon-basic-mail-open-text" => "basic-mail-open-text" ),
			array( "icon-basic-male" => "basic-male" ),
			array( "icon-basic-map" => "basic-map" ),
			array( "icon-basic-message" => "basic-message" ),
			array( "icon-basic-message-multiple" => "basic-message-multiple" ),
			array( "icon-basic-message-txt" => "basic-message-txt" ),
			array( "icon-basic-mixer2" => "basic-mixer2" ),
			array( "icon-basic-mouse" => "basic-mouse" ),
			array( "icon-basic-notebook" => "basic-notebook" ),
			array( "icon-basic-notebook-pen" => "basic-notebook-pen" ),
			array( "icon-basic-notebook-pencil" => "basic-notebook-pencil" ),
			array( "icon-basic-paperplane" => "basic-paperplane" ),
			array( "icon-basic-pencil-ruler" => "basic-pencil-ruler" ),
			array( "icon-basic-pencil-ruler-pen" => "basic-pencil-ruler-pen" ),
			array( "icon-basic-photo" => "basic-photo" ),
			array( "icon-basic-picture" => "basic-picture" ),
			array( "icon-basic-picture-multiple" => "basic-picture-multiple" ),
			array( "icon-basic-pin1" => "basic-pin1" ),
			array( "icon-basic-pin2" => "basic-pin2" ),
			array( "icon-basic-postcard" => "basic-postcard" ),
			array( "icon-basic-postcard-multiple" => "basic-postcard-multiple" ),
			array( "icon-basic-printer" => "basic-printer" ),
			array( "icon-basic-question" => "basic-question" ),
			array( "icon-basic-rss" => "basic-rss" ),
			array( "icon-basic-server" => "basic-server" ),
			array( "icon-basic-server2" => "basic-server2" ),
			array( "icon-basic-server-cloud" => "basic-server-cloud" ),
			array( "icon-basic-server-download" => "basic-server-download" ),
			array( "icon-basic-server-upload" => "basic-server-upload" ),
			array( "icon-basic-settings" => "basic-settings" ),
			array( "icon-basic-share" => "basic-share" ),
			array( "icon-basic-sheet" => "basic-sheet" ),
			array( "icon-basic-sheet-multiple" => "basic-sheet-multiple" ),
			array( "icon-basic-sheet-pen" => "basic-sheet-pen" ),
			array( "icon-basic-sheet-pencil" => "basic-sheet-pencil" ),
			array( "icon-basic-sheet-txt" => "basic-sheet-txt" ),
			array( "icon-basic-signs" => "basic-signs" ),
			array( "icon-basic-smartphone" => "basic-smartphone" ),
			array( "icon-basic-spades" => "basic-spades" ),
			array( "icon-basic-spread" => "basic-spread" ),
			array( "icon-basic-spread-bookmark" => "basic-spread-bookmark" ),
			array( "icon-basic-spread-text" => "basic-spread-text" ),
			array( "icon-basic-spread-text-bookmark" => "basic-spread-text-bookmark" ),
			array( "icon-basic-star" => "basic-star" ),
			array( "icon-basic-tablet" => "basic-tablet" ),
			array( "icon-basic-target" => "basic-target" ),
			array( "icon-basic-todo" => "basic-todo" ),
			array( "icon-basic-todo-pen" => "basic-todo-pen" ),
			array( "icon-basic-todo-pencil" => "basic-todo-pencil" ),
			array( "icon-basic-todo-txt" => "basic-todo-txt" ),
			array( "icon-basic-todolist-pen" => "basic-todolist-pen" ),
			array( "icon-basic-todolist-pencil" => "basic-todolist-pencil" ),
			array( "icon-basic-trashcan" => "basic-trashcan" ),
			array( "icon-basic-trashcan-full" => "basic-trashcan-full" ),
			array( "icon-basic-trashcan-refresh" => "basic-trashcan-refresh" ),
			array( "icon-basic-trashcan-remove" => "basic-trashcan-remove" ),
			array( "icon-basic-upload" => "basic-upload" ),
			array( "icon-basic-usb" => "basic-usb" ),
			array( "icon-basic-video" => "basic-video" ),
			array( "icon-basic-watch" => "basic-watch" ),
			array( "icon-basic-webpage" => "basic-webpage" ),
			array( "icon-basic-webpage-img-txt" => "basic-webpage-img-txt" ),
			array( "icon-basic-webpage-multiple" => "basic-webpage-multiple" ),
			array( "icon-basic-webpage-txt" => "basic-webpage-txt" ),
			array( "icon-basic-world" => "basic-world" ),
		),
		'Basic Elaboration' => array(
			array( "icon-basic-elaboration-bookmark-checck" => "basic-elaboration-bookmark-checck" ),
			array( "icon-basic-elaboration-bookmark-minus" => "basic-elaboration-bookmark-minus" ),
			array( "icon-basic-elaboration-bookmark-plus" => "basic-elaboration-bookmark-plus" ),
			array( "icon-basic-elaboration-bookmark-remove" => "basic-elaboration-bookmark-remove" ),
			array( "icon-basic-elaboration-briefcase-check" => "basic-elaboration-briefcase-check" ),
			array( "icon-basic-elaboration-briefcase-download" => "basic-elaboration-briefcase-download" ),
			array( "icon-basic-elaboration-briefcase-flagged" => "basic-elaboration-briefcase-flagged" ),
			array( "icon-basic-elaboration-briefcase-minus" => "basic-elaboration-briefcase-minus" ),
			array( "icon-basic-elaboration-briefcase-plus" => "basic-elaboration-briefcase-plus" ),
			array( "icon-basic-elaboration-briefcase-refresh" => "basic-elaboration-briefcase-refresh" ),
			array( "icon-basic-elaboration-briefcase-remove" => "basic-elaboration-briefcase-remove" ),
			array( "icon-basic-elaboration-briefcase-search" => "basic-elaboration-briefcase-search" ),
			array( "icon-basic-elaboration-briefcase-star" => "basic-elaboration-briefcase-star" ),
			array( "icon-basic-elaboration-briefcase-upload" => "basic-elaboration-briefcase-upload" ),
			array( "icon-basic-elaboration-browser-check" => "basic-elaboration-browser-check" ),
			array( "icon-basic-elaboration-browser-download" => "basic-elaboration-browser-download" ),
			array( "icon-basic-elaboration-browser-minus" => "basic-elaboration-browser-minus" ),
			array( "icon-basic-elaboration-browser-plus" => "basic-elaboration-browser-plus" ),
			array( "icon-basic-elaboration-browser-refresh" => "basic-elaboration-browser-refresh" ),
			array( "icon-basic-elaboration-browser-remove" => "basic-elaboration-browser-remove" ),
			array( "icon-basic-elaboration-browser-search" => "basic-elaboration-browser-search" ),
			array( "icon-basic-elaboration-browser-star" => "basic-elaboration-browser-star" ),
			array( "icon-basic-elaboration-browser-upload" => "basic-elaboration-browser-upload" ),
			array( "icon-basic-elaboration-calendar-check" => "basic-elaboration-calendar-check" ),
			array( "icon-basic-elaboration-calendar-cloud" => "basic-elaboration-calendar-cloud" ),
			array( "icon-basic-elaboration-calendar-download" => "basic-elaboration-calendar-download" ),
			array( "icon-basic-elaboration-calendar-empty" => "basic-elaboration-calendar-empty" ),
			array( "icon-basic-elaboration-calendar-flagged" => "basic-elaboration-calendar-flagged" ),
			array( "icon-basic-elaboration-calendar-heart" => "basic-elaboration-calendar-heart" ),
			array( "icon-basic-elaboration-calendar-minus" => "basic-elaboration-calendar-minus" ),
			array( "icon-basic-elaboration-calendar-next" => "basic-elaboration-calendar-next" ),
			array( "icon-basic-elaboration-calendar-noaccess" => "basic-elaboration-calendar-noaccess" ),
			array( "icon-basic-elaboration-calendar-pencil" => "basic-elaboration-calendar-pencil" ),
			array( "icon-basic-elaboration-calendar-plus" => "basic-elaboration-calendar-plus" ),
			array( "icon-basic-elaboration-calendar-previous" => "basic-elaboration-calendar-previous" ),
			array( "icon-basic-elaboration-calendar-refresh" => "basic-elaboration-calendar-refresh" ),
			array( "icon-basic-elaboration-calendar-remove" => "basic-elaboration-calendar-remove" ),
			array( "icon-basic-elaboration-calendar-search" => "basic-elaboration-calendar-search" ),
			array( "icon-basic-elaboration-calendar-star" => "basic-elaboration-calendar-star" ),
			array( "icon-basic-elaboration-calendar-upload" => "basic-elaboration-calendar-upload" ),
			array( "icon-basic-elaboration-cloud-check" => "basic-elaboration-cloud-check" ),
			array( "icon-basic-elaboration-cloud-download" => "basic-elaboration-cloud-download" ),
			array( "icon-basic-elaboration-cloud-minus" => "basic-elaboration-cloud-minus" ),
			array( "icon-basic-elaboration-cloud-noaccess" => "basic-elaboration-cloud-noaccess" ),
			array( "icon-basic-elaboration-cloud-plus" => "basic-elaboration-cloud-plus" ),
			array( "icon-basic-elaboration-cloud-refresh" => "basic-elaboration-cloud-refresh" ),
			array( "icon-basic-elaboration-cloud-remove" => "basic-elaboration-cloud-remove" ),
			array( "icon-basic-elaboration-cloud-search" => "basic-elaboration-cloud-search" ),
			array( "icon-basic-elaboration-cloud-upload" => "basic-elaboration-cloud-upload" ),
			array( "icon-basic-elaboration-document-check" => "basic-elaboration-document-check" ),
			array( "icon-basic-elaboration-document-cloud" => "basic-elaboration-document-cloud" ),
			array( "icon-basic-elaboration-document-download" => "basic-elaboration-document-download" ),
			array( "icon-basic-elaboration-document-flagged" => "basic-elaboration-document-flagged" ),
			array( "icon-basic-elaboration-document-graph" => "basic-elaboration-document-graph" ),
			array( "icon-basic-elaboration-document-heart" => "basic-elaboration-document-heart" ),
			array( "icon-basic-elaboration-document-minus" => "basic-elaboration-document-minus" ),
			array( "icon-basic-elaboration-document-next" => "basic-elaboration-document-next" ),
			array( "icon-basic-elaboration-document-noaccess" => "basic-elaboration-document-noaccess" ),
			array( "icon-basic-elaboration-document-note" => "basic-elaboration-document-note" ),
			array( "icon-basic-elaboration-document-pencil" => "basic-elaboration-document-pencil" ),
			array( "icon-basic-elaboration-document-picture" => "basic-elaboration-document-picture" ),
			array( "icon-basic-elaboration-document-plus" => "basic-elaboration-document-plus" ),
			array( "icon-basic-elaboration-document-previous" => "basic-elaboration-document-previous" ),
			array( "icon-basic-elaboration-document-refresh" => "basic-elaboration-document-refresh" ),
			array( "icon-basic-elaboration-document-remove" => "basic-elaboration-document-remove" ),
			array( "icon-basic-elaboration-document-search" => "basic-elaboration-document-search" ),
			array( "icon-basic-elaboration-document-star" => "basic-elaboration-document-star" ),
			array( "icon-basic-elaboration-document-upload" => "basic-elaboration-document-upload" ),
			array( "icon-basic-elaboration-folder-check" => "basic-elaboration-folder-check" ),
			array( "icon-basic-elaboration-folder-cloud" => "basic-elaboration-folder-cloud" ),
			array( "icon-basic-elaboration-folder-document" => "basic-elaboration-folder-document" ),
			array( "icon-basic-elaboration-folder-download" => "basic-elaboration-folder-download" ),
			array( "icon-basic-elaboration-folder-flagged" => "basic-elaboration-folder-flagged" ),
			array( "icon-basic-elaboration-folder-graph" => "basic-elaboration-folder-graph" ),
			array( "icon-basic-elaboration-folder-heart" => "basic-elaboration-folder-heart" ),
			array( "icon-basic-elaboration-folder-minus" => "basic-elaboration-folder-minus" ),
			array( "icon-basic-elaboration-folder-next" => "basic-elaboration-folder-next" ),
			array( "icon-basic-elaboration-folder-noaccess" => "basic-elaboration-folder-noaccess" ),
			array( "icon-basic-elaboration-folder-note" => "basic-elaboration-folder-note" ),
			array( "icon-basic-elaboration-folder-pencil" => "basic-elaboration-folder-pencil" ),
			array( "icon-basic-elaboration-folder-picture" => "basic-elaboration-folder-picture" ),
			array( "icon-basic-elaboration-folder-plus" => "basic-elaboration-folder-plus" ),
			array( "icon-basic-elaboration-folder-previous" => "basic-elaboration-folder-previous" ),
			array( "icon-basic-elaboration-folder-refresh" => "basic-elaboration-folder-refresh" ),
			array( "icon-basic-elaboration-folder-remove" => "basic-elaboration-folder-remove" ),
			array( "icon-basic-elaboration-folder-search" => "basic-elaboration-folder-search" ),
			array( "icon-basic-elaboration-folder-star" => "basic-elaboration-folder-star" ),
			array( "icon-basic-elaboration-folder-upload" => "basic-elaboration-folder-upload" ),
			array( "icon-basic-elaboration-mail-check" => "basic-elaboration-mail-check" ),
			array( "icon-basic-elaboration-mail-cloud" => "basic-elaboration-mail-cloud" ),
			array( "icon-basic-elaboration-mail-document" => "basic-elaboration-mail-document" ),
			array( "icon-basic-elaboration-mail-download" => "basic-elaboration-mail-download" ),
			array( "icon-basic-elaboration-mail-flagged" => "basic-elaboration-mail-flagged" ),
			array( "icon-basic-elaboration-mail-heart" => "basic-elaboration-mail-heart" ),
			array( "icon-basic-elaboration-mail-next" => "basic-elaboration-mail-next" ),
			array( "icon-basic-elaboration-mail-noaccess" => "basic-elaboration-mail-noaccess" ),
			array( "icon-basic-elaboration-mail-note" => "basic-elaboration-mail-note" ),
			array( "icon-basic-elaboration-mail-pencil" => "basic-elaboration-mail-pencil" ),
			array( "icon-basic-elaboration-mail-picture" => "basic-elaboration-mail-picture" ),
			array( "icon-basic-elaboration-mail-previous" => "basic-elaboration-mail-previous" ),
			array( "icon-basic-elaboration-mail-refresh" => "basic-elaboration-mail-refresh" ),
			array( "icon-basic-elaboration-mail-remove" => "basic-elaboration-mail-remove" ),
			array( "icon-basic-elaboration-mail-search" => "basic-elaboration-mail-search" ),
			array( "icon-basic-elaboration-mail-star" => "basic-elaboration-mail-star" ),
			array( "icon-basic-elaboration-mail-upload" => "basic-elaboration-mail-upload" ),
			array( "icon-basic-elaboration-message-check" => "basic-elaboration-message-check" ),
			array( "icon-basic-elaboration-message-dots" => "basic-elaboration-message-dots" ),
			array( "icon-basic-elaboration-message-happy" => "basic-elaboration-message-happy" ),
			array( "icon-basic-elaboration-message-heart" => "basic-elaboration-message-heart" ),
			array( "icon-basic-elaboration-message-minus" => "basic-elaboration-message-minus" ),
			array( "icon-basic-elaboration-message-note" => "basic-elaboration-message-note" ),
			array( "icon-basic-elaboration-message-plus" => "basic-elaboration-message-plus" ),
			array( "icon-basic-elaboration-message-refresh" => "basic-elaboration-message-refresh" ),
			array( "icon-basic-elaboration-message-remove" => "basic-elaboration-message-remove" ),
			array( "icon-basic-elaboration-message-sad" => "basic-elaboration-message-sad" ),
			array( "icon-basic-elaboration-smartphone-cloud" => "basic-elaboration-smartphone-cloud" ),
			array( "icon-basic-elaboration-smartphone-heart" => "basic-elaboration-smartphone-heart" ),
			array( "icon-basic-elaboration-smartphone-noaccess" => "basic-elaboration-smartphone-noaccess" ),
			array( "icon-basic-elaboration-smartphone-note" => "basic-elaboration-smartphone-note" ),
			array( "icon-basic-elaboration-smartphone-pencil" => "basic-elaboration-smartphone-pencil" ),
			array( "icon-basic-elaboration-smartphone-picture" => "basic-elaboration-smartphone-picture" ),
			array( "icon-basic-elaboration-smartphone-refresh" => "basic-elaboration-smartphone-refresh" ),
			array( "icon-basic-elaboration-smartphone-search" => "basic-elaboration-smartphone-search" ),
			array( "icon-basic-elaboration-tablet-cloud" => "basic-elaboration-tablet-cloud" ),
			array( "icon-basic-elaboration-tablet-heart" => "basic-elaboration-tablet-heart" ),
			array( "icon-basic-elaboration-tablet-noaccess" => "basic-elaboration-tablet-noaccess" ),
			array( "icon-basic-elaboration-tablet-note" => "basic-elaboration-tablet-note" ),
			array( "icon-basic-elaboration-tablet-pencil" => "basic-elaboration-tablet-pencil" ),
			array( "icon-basic-elaboration-tablet-picture" => "basic-elaboration-tablet-picture" ),
			array( "icon-basic-elaboration-tablet-refresh" => "basic-elaboration-tablet-refresh" ),
			array( "icon-basic-elaboration-tablet-search" => "basic-elaboration-tablet-search" ),
			array( "icon-basic-elaboration-todolist-2" => "basic-elaboration-todolist-2" ),
			array( "icon-basic-elaboration-todolist-check" => "basic-elaboration-todolist-check" ),
			array( "icon-basic-elaboration-todolist-cloud" => "basic-elaboration-todolist-cloud" ),
			array( "icon-basic-elaboration-todolist-download" => "basic-elaboration-todolist-download" ),
			array( "icon-basic-elaboration-todolist-flagged" => "basic-elaboration-todolist-flagged" ),
			array( "icon-basic-elaboration-todolist-minus" => "basic-elaboration-todolist-minus" ),
			array( "icon-basic-elaboration-todolist-noaccess" => "basic-elaboration-todolist-noaccess" ),
			array( "icon-basic-elaboration-todolist-pencil" => "basic-elaboration-todolist-pencil" ),
			array( "icon-basic-elaboration-todolist-plus" => "basic-elaboration-todolist-plus" ),
			array( "icon-basic-elaboration-todolist-refresh" => "basic-elaboration-todolist-refresh" ),
			array( "icon-basic-elaboration-todolist-remove" => "basic-elaboration-todolist-remove" ),
			array( "icon-basic-elaboration-todolist-search" => "basic-elaboration-todolist-search" ),
			array( "icon-basic-elaboration-todolist-star" => "basic-elaboration-todolist-star" ),
			array( "icon-basic-elaboration-todolist-upload" => "basic-elaboration-todolist-upload" )
		),
		'Ecommerce' => array(
			array( "icon-ecommerce-bag" => "ecommerce-bag" ),
			array( "icon-ecommerce-bag-check" => "ecommerce-bag-check" ),
			array( "icon-ecommerce-bag-cloud" => "ecommerce-bag-cloud" ),
			array( "icon-ecommerce-bag-download" => "ecommerce-bag-download" ),
			array( "icon-ecommerce-bag-minus" => "ecommerce-bag-minus" ),
			array( "icon-ecommerce-bag-plus" => "ecommerce-bag-plus" ),
			array( "icon-ecommerce-bag-refresh" => "ecommerce-bag-refresh" ),
			array( "icon-ecommerce-bag-remove" => "ecommerce-bag-remove" ),
			array( "icon-ecommerce-bag-search" => "ecommerce-bag-search" ),
			array( "icon-ecommerce-bag-upload" => "ecommerce-bag-upload" ),
			array( "icon-ecommerce-banknote" => "ecommerce-banknote" ),
			array( "icon-ecommerce-banknotes" => "ecommerce-banknotes" ),
			array( "icon-ecommerce-basket" => "ecommerce-basket" ),
			array( "icon-ecommerce-basket-check" => "ecommerce-basket-check" ),
			array( "icon-ecommerce-basket-cloud" => "ecommerce-basket-cloud" ),
			array( "icon-ecommerce-basket-download" => "ecommerce-basket-download" ),
			array( "icon-ecommerce-basket-minus" => "ecommerce-basket-minus" ),
			array( "icon-ecommerce-basket-plus" => "ecommerce-basket-plus" ),
			array( "icon-ecommerce-basket-refresh" => "ecommerce-basket-refresh" ),
			array( "icon-ecommerce-basket-remove" => "ecommerce-basket-remove" ),
			array( "icon-ecommerce-basket-search" => "ecommerce-basket-search" ),
			array( "icon-ecommerce-basket-upload" => "ecommerce-basket-upload" ),
			array( "icon-ecommerce-bath" => "ecommerce-bath" ),
			array( "icon-ecommerce-cart" => "ecommerce-cart" ),
			array( "icon-ecommerce-cart-check" => "ecommerce-cart-check" ),
			array( "icon-ecommerce-cart-cloud" => "ecommerce-cart-cloud" ),
			array( "icon-ecommerce-cart-content" => "ecommerce-cart-content" ),
			array( "icon-ecommerce-cart-download" => "ecommerce-cart-download" ),
			array( "icon-ecommerce-cart-minus" => "ecommerce-cart-minus" ),
			array( "icon-ecommerce-cart-plus" => "ecommerce-cart-plus" ),
			array( "icon-ecommerce-cart-refresh" => "ecommerce-cart-refresh" ),
			array( "icon-ecommerce-cart-remove" => "ecommerce-cart-remove" ),
			array( "icon-ecommerce-cart-search" => "ecommerce-cart-search" ),
			array( "icon-ecommerce-cart-upload" => "ecommerce-cart-upload" ),
			array( "icon-ecommerce-cent" => "ecommerce-cent" ),
			array( "icon-ecommerce-colon" => "ecommerce-colon" ),
			array( "icon-ecommerce-creditcard" => "ecommerce-creditcard" ),
			array( "icon-ecommerce-diamond" => "ecommerce-diamond" ),
			array( "icon-ecommerce-dollar" => "ecommerce-dollar" ),
			array( "icon-ecommerce-euro" => "ecommerce-euro" ),
			array( "icon-ecommerce-franc" => "ecommerce-franc" ),
			array( "icon-ecommerce-gift" => "ecommerce-gift" ),
			array( "icon-ecommerce-graph1" => "ecommerce-graph1" ),
			array( "icon-ecommerce-graph2" => "ecommerce-graph2" ),
			array( "icon-ecommerce-graph3" => "ecommerce-graph3" ),
			array( "icon-ecommerce-graph-decrease" => "ecommerce-graph-decrease" ),
			array( "icon-ecommerce-graph-increase" => "ecommerce-graph-increase" ),
			array( "icon-ecommerce-guarani" => "ecommerce-guarani" ),
			array( "icon-ecommerce-kips" => "ecommerce-kips" ),
			array( "icon-ecommerce-lira" => "ecommerce-lira" ),
			array( "icon-ecommerce-megaphone" => "ecommerce-megaphone" ),
			array( "icon-ecommerce-money" => "ecommerce-money" ),
			array( "icon-ecommerce-naira" => "ecommerce-naira" ),
			array( "icon-ecommerce-pesos" => "ecommerce-pesos" ),
			array( "icon-ecommerce-pound" => "ecommerce-pound" ),
			array( "icon-ecommerce-receipt" => "ecommerce-receipt" ),
			array( "icon-ecommerce-receipt-bath" => "ecommerce-receipt-bath" ),
			array( "icon-ecommerce-receipt-cent" => "ecommerce-receipt-cent" ),
			array( "icon-ecommerce-receipt-dollar" => "ecommerce-receipt-dollar" ),
			array( "icon-ecommerce-receipt-euro" => "ecommerce-receipt-euro" ),
			array( "icon-ecommerce-receipt-franc" => "ecommerce-receipt-franc" ),
			array( "icon-ecommerce-receipt-guarani" => "ecommerce-receipt-guarani" ),
			array( "icon-ecommerce-receipt-kips" => "ecommerce-receipt-kips" ),
			array( "icon-ecommerce-receipt-lira" => "ecommerce-receipt-lira" ),
			array( "icon-ecommerce-receipt-naira" => "ecommerce-receipt-naira" ),
			array( "icon-ecommerce-receipt-pesos" => "ecommerce-receipt-pesos" ),
			array( "icon-ecommerce-receipt-pound" => "ecommerce-receipt-pound" ),
			array( "icon-ecommerce-receipt-rublo" => "ecommerce-receipt-rublo" ),
			array( "icon-ecommerce-receipt-rupee" => "ecommerce-receipt-rupee" ),
			array( "icon-ecommerce-receipt-tugrik" => "ecommerce-receipt-tugrik" ),
			array( "icon-ecommerce-receipt-won" => "ecommerce-receipt-won" ),
			array( "icon-ecommerce-receipt-yen" => "ecommerce-receipt-yen" ),
			array( "icon-ecommerce-receipt-yen2" => "ecommerce-receipt-yen2" ),
			array( "icon-ecommerce-recept-colon" => "ecommerce-recept-colon" ),
			array( "icon-ecommerce-rublo" => "ecommerce-rublo" ),
			array( "icon-ecommerce-rupee" => "ecommerce-rupee" ),
			array( "icon-ecommerce-safe" => "ecommerce-safe" ),
			array( "icon-ecommerce-sale" => "ecommerce-sale" ),
			array( "icon-ecommerce-sales" => "ecommerce-sales" ),
			array( "icon-ecommerce-ticket" => "ecommerce-ticket" ),
			array( "icon-ecommerce-tugriks" => "ecommerce-tugriks" ),
			array( "icon-ecommerce-wallet" => "ecommerce-wallet" ),
			array( "icon-ecommerce-won" => "ecommerce-won" ),
			array( "icon-ecommerce-yen" => "ecommerce-yen" ),
			array( "icon-ecommerce-yen2" => "ecommerce-yen2" )
		),
		'Music' => array(
			array( "icon-music-beginning-button" => "music-beginning-button" ),
			array( "icon-music-bell" => "music-bell" ),
			array( "icon-music-cd" => "music-cd" ),
			array( "icon-music-diapason" => "music-diapason" ),
			array( "icon-music-eject-button" => "music-eject-button" ),
			array( "icon-music-end-button" => "music-end-button" ),
			array( "icon-music-fastforward-button" => "music-fastforward-button" ),
			array( "icon-music-headphones" => "music-headphones" ),
			array( "icon-music-ipod" => "music-ipod" ),
			array( "icon-music-loudspeaker" => "music-loudspeaker" ),
			array( "icon-music-microphone" => "music-microphone" ),
			array( "icon-music-microphone-old" => "music-microphone-old" ),
			array( "icon-music-mixer" => "music-mixer" ),
			array( "icon-music-mute" => "music-mute" ),
			array( "icon-music-note-multiple" => "music-note-multiple" ),
			array( "icon-music-note-single" => "music-note-single" ),
			array( "icon-music-pause-button" => "music-pause-button" ),
			array( "icon-music-play-button" => "music-play-button" ),
			array( "icon-music-playlist" => "music-playlist" ),
			array( "icon-music-radio-ghettoblaster" => "music-radio-ghettoblaster" ),
			array( "icon-music-radio-portable" => "music-radio-portable" ),
			array( "icon-music-record" => "music-record" ),
			array( "icon-music-recordplayer" => "music-recordplayer" ),
			array( "icon-music-repeat-button" => "music-repeat-button" ),
			array( "icon-music-rewind-button" => "music-rewind-button" ),
			array( "icon-music-shuffle-button" => "music-shuffle-button" ),
			array( "icon-music-stop-button" => "music-stop-button" ),
			array( "icon-music-tape" => "music-tape" ),
			array( "icon-music-volume-down" => "music-volume-down" ),
			array( "icon-music-volume-up" => "music-volume-up" )
		),
		'Software' => array(
			array( "icon-software-add-vectorpoint" => "software-add-vectorpoint" ),
			array( "icon-software-box-oval" => "software-box-oval" ),
			array( "icon-software-box-polygon" => "software-box-polygon" ),
			array( "icon-software-box-rectangle" => "software-box-rectangle" ),
			array( "icon-software-box-roundedrectangle" => "software-box-roundedrectangle" ),
			array( "icon-software-character" => "software-character" ),
			array( "icon-software-crop" => "software-crop" ),
			array( "icon-software-eyedropper" => "software-eyedropper" ),
			array( "icon-software-font-allcaps" => "software-font-allcaps" ),
			array( "icon-software-font-baseline-shift" => "software-font-baseline-shift" ),
			array( "icon-software-font-horizontal-scale" => "software-font-horizontal-scale" ),
			array( "icon-software-font-kerning" => "software-font-kerning" ),
			array( "icon-software-font-leading" => "software-font-leading" ),
			array( "icon-software-font-size" => "software-font-size" ),
			array( "icon-software-font-smallcapital" => "software-font-smallcapital" ),
			array( "icon-software-font-smallcaps" => "software-font-smallcaps" ),
			array( "icon-software-font-strikethrough" => "software-font-strikethrough" ),
			array( "icon-software-font-tracking" => "software-font-tracking" ),
			array( "icon-software-font-underline" => "software-font-underline" ),
			array( "icon-software-font-vertical-scale" => "software-font-vertical-scale" ),
			array( "icon-software-horizontal-align-center" => "software-horizontal-align-center" ),
			array( "icon-software-horizontal-align-left" => "software-horizontal-align-left" ),
			array( "icon-software-horizontal-align-right" => "software-horizontal-align-right" ),
			array( "icon-software-horizontal-distribute-center" => "software-horizontal-distribute-center" ),
			array( "icon-software-horizontal-distribute-left" => "software-horizontal-distribute-left" ),
			array( "icon-software-horizontal-distribute-right" => "software-horizontal-distribute-right" ),
			array( "icon-software-indent-firstline" => "software-indent-firstline" ),
			array( "icon-software-indent-left" => "software-indent-left" ),
			array( "icon-software-indent-right" => "software-indent-right" ),
			array( "icon-software-lasso" => "software-lasso" ),
			array( "icon-software-layers1" => "software-layers1" ),
			array( "icon-software-layers2" => "software-layers2" ),
			array( "icon-software-layout" => "software-layout" ),
			array( "icon-software-layout-2columns" => "software-layout-2columns" ),
			array( "icon-software-layout-3columns" => "software-layout-3columns" ),
			array( "icon-software-layout-4boxes" => "software-layout-4boxes" ),
			array( "icon-software-layout-4columns" => "software-layout-4columns" ),
			array( "icon-software-layout-4lines" => "software-layout-4lines" ),
			array( "icon-software-layout-8boxes" => "software-layout-8boxes" ),
			array( "icon-software-layout-header" => "software-layout-header" ),
			array( "icon-software-layout-header-2columns" => "software-layout-header-2columns" ),
			array( "icon-software-layout-header-3columns" => "software-layout-header-3columns" ),
			array( "icon-software-layout-header-4boxes" => "software-layout-header-4boxes" ),
			array( "icon-software-layout-header-4columns" => "software-layout-header-4columns" ),
			array( "icon-software-layout-header-complex" => "software-layout-header-complex" ),
			array( "icon-software-layout-header-complex2" => "software-layout-header-complex2" ),
			array( "icon-software-layout-header-complex3" => "software-layout-header-complex3" ),
			array( "icon-software-layout-header-complex4" => "software-layout-header-complex4" ),
			array( "icon-software-layout-header-sideleft" => "software-layout-header-sideleft" ),
			array( "icon-software-layout-header-sideright" => "software-layout-header-sideright" ),
			array( "icon-software-layout-sidebar-left" => "software-layout-sidebar-left" ),
			array( "icon-software-layout-sidebar-right" => "software-layout-sidebar-right" ),
			array( "icon-software-magnete" => "software-magnete" ),
			array( "icon-software-pages" => "software-pages" ),
			array( "icon-software-paintbrush" => "software-paintbrush" ),
			array( "icon-software-paintbucket" => "software-paintbucket" ),
			array( "icon-software-paintroller" => "software-paintroller" ),
			array( "icon-software-paragraph" => "software-paragraph" ),
			array( "icon-software-paragraph-align-left" => "software-paragraph-align-left" ),
			array( "icon-software-paragraph-align-right" => "software-paragraph-align-right" ),
			array( "icon-software-paragraph-center" => "software-paragraph-center" ),
			array( "icon-software-paragraph-justify-all" => "software-paragraph-justify-all" ),
			array( "icon-software-paragraph-justify-center" => "software-paragraph-justify-center" ),
			array( "icon-software-paragraph-justify-left" => "software-paragraph-justify-left" ),
			array( "icon-software-paragraph-justify-right" => "software-paragraph-justify-right" ),
			array( "icon-software-paragraph-space-after" => "software-paragraph-space-after" ),
			array( "icon-software-paragraph-space-before" => "software-paragraph-space-before" ),
			array( "icon-software-pathfinder-exclude" => "software-pathfinder-exclude" ),
			array( "icon-software-pathfinder-intersect" => "software-pathfinder-intersect" ),
			array( "icon-software-pathfinder-subtract" => "software-pathfinder-subtract" ),
			array( "icon-software-pathfinder-unite" => "software-pathfinder-unite" ),
			array( "icon-software-pen" => "software-pen" ),
			array( "icon-software-pen-add" => "software-pen-add" ),
			array( "icon-software-pen-remove" => "software-pen-remove" ),
			array( "icon-software-pencil" => "software-pencil" ),
			array( "icon-software-polygonallasso" => "software-polygonallasso" ),
			array( "icon-software-reflect-horizontal" => "software-reflect-horizontal" ),
			array( "icon-software-reflect-vertical" => "software-reflect-vertical" ),
			array( "icon-software-remove-vectorpoint" => "software-remove-vectorpoint" ),
			array( "icon-software-scale-expand" => "software-scale-expand" ),
			array( "icon-software-scale-reduce" => "software-scale-reduce" ),
			array( "icon-software-selection-oval" => "software-selection-oval" ),
			array( "icon-software-selection-polygon" => "software-selection-polygon" ),
			array( "icon-software-selection-rectangle" => "software-selection-rectangle" ),
			array( "icon-software-selection-roundedrectangle" => "software-selection-roundedrectangle" ),
			array( "icon-software-shape-oval" => "software-shape-oval" ),
			array( "icon-software-shape-polygon" => "software-shape-polygon" ),
			array( "icon-software-shape-rectangle" => "software-shape-rectangle" ),
			array( "icon-software-shape-roundedrectangle" => "software-shape-roundedrectangle" ),
			array( "icon-software-slice" => "software-slice" ),
			array( "icon-software-transform-bezier" => "software-transform-bezier" ),
			array( "icon-software-vector-box" => "software-vector-box" ),
			array( "icon-software-vector-composite" => "software-vector-composite" ),
			array( "icon-software-vector-line" => "software-vector-line" ),
			array( "icon-software-vertical-align-bottom" => "software-vertical-align-bottom" ),
			array( "icon-software-vertical-align-center" => "software-vertical-align-center" ),
			array( "icon-software-vertical-align-top" => "software-vertical-align-top" ),
			array( "icon-software-vertical-distribute-bottom" => "software-vertical-distribute-bottom" ),
			array( "icon-software-vertical-distribute-center" => "software-vertical-distribute-center" ),
			array( "icon-software-vertical-distribute-top" => "software-vertical-distribute-top" )
		),
		'Weather' => array(
			array( "icon-weather-aquarius" => "weather-aquarius" ),
			array( "icon-weather-aries" => "weather-aries" ),
			array( "icon-weather-cancer" => "weather-cancer" ),
			array( "icon-weather-capricorn" => "weather-capricorn" ),
			array( "icon-weather-cloud" => "weather-cloud" ),
			array( "icon-weather-cloud-drop" => "weather-cloud-drop" ),
			array( "icon-weather-cloud-lightning" => "weather-cloud-lightning" ),
			array( "icon-weather-cloud-snowflake" => "weather-cloud-snowflake" ),
			array( "icon-weather-downpour-fullmoon" => "weather-downpour-fullmoon" ),
			array( "icon-weather-downpour-halfmoon" => "weather-downpour-halfmoon" ),
			array( "icon-weather-downpour-sun" => "weather-downpour-sun" ),
			array( "icon-weather-drop" => "weather-drop" ),
			array( "icon-weather-first-quarter" => "weather-first-quarter" ),
			array( "icon-weather-fog" => "weather-fog" ),
			array( "icon-weather-fog-fullmoon" => "weather-fog-fullmoon" ),
			array( "icon-weather-fog-halfmoon" => "weather-fog-halfmoon" ),
			array( "icon-weather-fog-sun" => "weather-fog-sun" ),
			array( "icon-weather-fullmoon" => "weather-fullmoon" ),
			array( "icon-weather-gemini" => "weather-gemini" ),
			array( "icon-weather-hail" => "weather-hail" ),
			array( "icon-weather-hail-fullmoon" => "weather-hail-fullmoon" ),
			array( "icon-weather-hail-halfmoon" => "weather-hail-halfmoon" ),
			array( "icon-weather-hail-sun" => "weather-hail-sun" ),
			array( "icon-weather-last-quarter" => "weather-last-quarter" ),
			array( "icon-weather-leo" => "weather-leo" ),
			array( "icon-weather-libra" => "weather-libra" ),
			array( "icon-weather-lightning" => "weather-lightning" ),
			array( "icon-weather-mistyrain" => "weather-mistyrain" ),
			array( "icon-weather-mistyrain-fullmoon" => "weather-mistyrain-fullmoon" ),
			array( "icon-weather-mistyrain-halfmoon" => "weather-mistyrain-halfmoon" ),
			array( "icon-weather-mistyrain-sun" => "weather-mistyrain-sun" ),
			array( "icon-weather-moon" => "weather-moon" ),
			array( "icon-weather-moondown-full" => "weather-moondown-full" ),
			array( "icon-weather-moondown-half" => "weather-moondown-half" ),
			array( "icon-weather-moonset-full" => "weather-moonset-full" ),
			array( "icon-weather-moonset-half" => "weather-moonset-half" ),
			array( "icon-weather-move2" => "weather-move2" ),
			array( "icon-weather-newmoon" => "weather-newmoon" ),
			array( "icon-weather-pisces" => "weather-pisces" ),
			array( "icon-weather-rain" => "weather-rain" ),
			array( "icon-weather-rain-fullmoon" => "weather-rain-fullmoon" ),
			array( "icon-weather-rain-halfmoon" => "weather-rain-halfmoon" ),
			array( "icon-weather-rain-sun" => "weather-rain-sun" ),
			array( "icon-weather-sagittarius" => "weather-sagittarius" ),
			array( "icon-weather-scorpio" => "weather-scorpio" ),
			array( "icon-weather-snow" => "weather-snow" ),
			array( "icon-weather-snow-fullmoon" => "weather-snow-fullmoon" ),
			array( "icon-weather-snow-halfmoon" => "weather-snow-halfmoon" ),
			array( "icon-weather-snow-sun" => "weather-snow-sun" ),
			array( "icon-weather-snowflake" => "weather-snowflake" ),
			array( "icon-weather-star" => "weather-star" ),
			array( "icon-weather-storm-11" => "weather-storm-11" ),
			array( "icon-weather-storm-32" => "weather-storm-32" ),
			array( "icon-weather-storm-fullmoon" => "weather-storm-fullmoon" ),
			array( "icon-weather-storm-halfmoon" => "weather-storm-halfmoon" ),
			array( "icon-weather-storm-sun" => "weather-storm-sun" ),
			array( "icon-weather-sun" => "weather-sun" ),
			array( "icon-weather-sundown" => "weather-sundown" ),
			array( "icon-weather-sunset" => "weather-sunset" ),
			array( "icon-weather-taurus" => "weather-taurus" ),
			array( "icon-weather-tempest" => "weather-tempest" ),
			array( "icon-weather-tempest-fullmoon" => "weather-tempest-fullmoon" ),
			array( "icon-weather-tempest-halfmoon" => "weather-tempest-halfmoon" ),
			array( "icon-weather-tempest-sun" => "weather-tempest-sun" ),
			array( "icon-weather-variable-fullmoon" => "weather-variable-fullmoon" ),
			array( "icon-weather-variable-halfmoon" => "weather-variable-halfmoon" ),
			array( "icon-weather-variable-sun" => "weather-variable-sun" ),
			array( "icon-weather-virgo" => "weather-virgo" ),
			array( "icon-weather-waning-cresent" => "weather-waning-cresent" ),
			array( "icon-weather-waning-gibbous" => "weather-waning-gibbous" ),
			array( "icon-weather-waxing-cresent" => "weather-waxing-cresent" ),
			array( "icon-weather-waxing-gibbous" => "weather-waxing-gibbous" ),
			array( "icon-weather-wind" => "weather-wind" ),
			array( "icon-weather-wind-e" => "weather-wind-e" ),
			array( "icon-weather-wind-fullmoon" => "weather-wind-fullmoon" ),
			array( "icon-weather-wind-halfmoon" => "weather-wind-halfmoon" ),
			array( "icon-weather-wind-n" => "weather-wind-n" ),
			array( "icon-weather-wind-ne" => "weather-wind-ne" ),
			array( "icon-weather-wind-nw" => "weather-wind-nw" ),
			array( "icon-weather-wind-s" => "weather-wind-s" ),
			array( "icon-weather-wind-se" => "weather-wind-se" ),
			array( "icon-weather-wind-sun" => "weather-wind-sun" ),
			array( "icon-weather-wind-sw" => "weather-wind-sw" ),
			array( "icon-weather-wind-w" => "weather-wind-w" ),
			array( "icon-weather-windgust" => "weather-windgust" )
		)
	
	);
	
	return array_merge( $icons, $linea_icons );

}

add_filter( 'vc_iconpicker-type-lineaicons', 'ut_iconpicker_type_lineaicons' );

function ut_linea_icon_register_css() {
    
    wp_register_style( 
        'ut-linea-arrows', 
        UT_SHORTCODES_URL . 'css/lineaicons/arrows/arrows.css'
    );
	
	wp_register_style( 
        'ut-linea-basic', 
        UT_SHORTCODES_URL . 'css/lineaicons/basic/basic.css'
    );
	
	wp_register_style( 
        'ut-linea-basic-elaboration', 
        UT_SHORTCODES_URL . 'css/lineaicons/basic-elaboration/basic-elaboration.css'
    );
	
	wp_register_style( 
        'ut-linea-ecommerce', 
        UT_SHORTCODES_URL . 'css/lineaicons/ecommerce/ecommerce.css'
    );
	
	wp_register_style( 
        'ut-linea-music', 
        UT_SHORTCODES_URL . 'css/lineaicons/music/music.css'
    );
	
	wp_register_style( 
        'ut-linea-software', 
        UT_SHORTCODES_URL . 'css/lineaicons/software/software.css'
    );
	
	wp_register_style( 
        'ut-linea-weather', 
        UT_SHORTCODES_URL . 'css/lineaicons/weather/weather.css'
    );

}

add_action( 'vc_base_register_admin_css', 'ut_linea_icon_register_css' );
    
function ut_enqueue_linea_icon_font() {

	wp_enqueue_style( 'ut-linea-arrows' );
	wp_enqueue_style( 'ut-linea-basic' );
	wp_enqueue_style( 'ut-linea-basic-elaboration' );
	wp_enqueue_style( 'ut-linea-ecommerce' );
	wp_enqueue_style( 'ut-linea-music' );
	wp_enqueue_style( 'ut-linea-software' );
	wp_enqueue_style( 'ut-linea-weather' );

}

add_action( 'vc_backend_editor_enqueue_js_css', 'ut_enqueue_linea_icon_font' );
add_action( 'vc_frontend_editor_enqueue_js_css', 'ut_enqueue_linea_icon_font' );
add_action( 'vc_enqueue_font_icon_element', 'ut_enqueue_linea_icon_font' );